/**
 * A user's bio — generated by AI or manually edited.
 * generatedAt is preserved across edits so we can always distinguish
 * "AI-generated" from "user-touched" content.
 */
export interface Bio {
  text: string;
  /** Unix timestamp (ms) when AI first generated this bio */
  generatedAt: number;
  /** Unix timestamp (ms) of the most recent manual edit, if any */
  editedAt?: number;
}

/**
 * A single album caption — one per top album.
 */
export interface Caption {
  albumId: string;
  text: string;
  /** Unix timestamp (ms) when AI first generated this caption */
  generatedAt: number;
  /** Unix timestamp (ms) of the most recent manual edit, if any */
  editedAt?: number;
}

/**
 * Combined content snapshot returned by getContent().
 * bio is null when no bio has ever been generated.
 */
export interface ContentData {
  bio: Bio | null;
  captions: Caption[];
}

/**
 * Music taste analysis — a fun, critic-informed review of the user's music taste.
 * Generated by AI, displayed on dashboard (not published to public profile yet).
 */
export interface TasteAnalysis {
  version: string;
  overall: {
    light: "green" | "amber" | "red";
    score: number;
    one_liner: string;
    confidence: number;
  };
  summary: {
    critic_vibe: string[];
    tags: string[];
    taste_arc: string;
  };
  breakdown: {
    artists: Array<{
      name: string;
      source_bucket: string[];
      light: "green" | "amber" | "red";
      confidence: number;
      reasons: string[];
    }>;
    albums: Array<{
      artist: string;
      title: string;
      light: "green" | "amber" | "red";
      confidence: number;
      reasons: string[];
    }>;
  };
  insights: {
    green_flags: string[];
    amber_flags: string[];
    red_flags: string[];
  };
  recommendations: Array<{
    because: string;
    picks: Array<{
      artist: string;
      title?: string;
    }>;
  }>;
  warnings: {
    no_web_lookup: boolean;
    no_numeric_ratings_claimed: boolean;
  };
  generatedAt: number;
}

/**
 * Age guess based on music taste — a playful inference, not a demographic fact.
 * Generated by AI, displayed on dashboard only.
 */
export interface AgeGuess {
  version: string;
  age_guess: {
    primary_range: string;
    confidence: number;
    generation_vibe: string;
    reasoning: string[];
  };
  alternate_ranges: Array<{
    range: string;
    confidence: number;
    why: string;
  }>;
  signals: {
    nostalgia_weight: number;
    discovery_weight: number;
    album_orientation: number;
    playlist_orientation: number;
  };
  disclaimers: {
    playful_inference: boolean;
    not_a_demographic_fact: boolean;
  };
  generatedAt: number;
}
