/**
 * A user's bio — generated by AI or manually edited.
 * generatedAt is preserved across edits so we can always distinguish
 * "AI-generated" from "user-touched" content.
 */
export interface Bio {
  text: string;
  /** Unix timestamp (ms) when AI first generated this bio */
  generatedAt: number;
  /** Unix timestamp (ms) of the most recent manual edit, if any */
  editedAt?: number;
}

/**
 * A single album caption — one per top album.
 */
export interface Caption {
  albumId: string;
  text: string;
  /** Unix timestamp (ms) when AI first generated this caption */
  generatedAt: number;
  /** Unix timestamp (ms) of the most recent manual edit, if any */
  editedAt?: number;
}

/**
 * Combined content snapshot returned by getContent().
 * bio is null when no bio has ever been generated.
 */
export interface ContentData {
  bio: Bio | null;
  captions: Caption[];
}
